### PR TITLE
Theme more variables, make scrollbar semi-transparent

### PR DESCRIPTION
**Pull request by elsmr**
👋

I noticed some git colors weren't themed, and the scrollbar blocked my view of the "markers" there.
I tried to fix it in this PR, let me know what you think.

### CODE REVIEW

**Comment by tobiastimm** [comment]
hey 😄 thanks for your pr. 

Could you post a before and after screen? would be great

**Comment by eliasmeire** [comment]
np 😄here's a before and after:

## Before

screen shot 2018-06-18 at 22 49 45

## After

screen shot 2018-06-18 at 22 50 27

Check out the colors in the gutter and under the scroll bar (Before they were hidden because the scrollbar was fully opaque)

**Comment by tobiastimm** [comment]
Looking good. Could you add these to the other variants too?

**Comment by eliasmeire** [comment]
Sure, i'll check it out later.

Yeah not sure why the JSX is looking like that 😛. I just checked and in Typescript React it's fine, Javascript React looks like this. No weird babel plugins btw. Can you check that one?

**Comment by tobiastimm** [comment]
@eliasmeire it is the [Sublime Babel](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) plugin that removes this weird look on jsx. I will create an issue to not depend on that plugin for proper styling.

**Comment by tobiastimm** [comment]
@eliasmeire I've pushed some fixes for #14. Are the jsx styles working for you now?

**Comment by eliasmeire** [comment]
Yes JSX looks nice now :) thanks. Sorry that i'm taking a while, i'll take some time to add it for the other themes tomorrow.

**Comment by eliasmeire** [comment]
```
Finally got around to it :P. Anyway for the other themes I used these colors I found in the tokenColors because they don't have red and green colors.


{
  "name": "Inserted",
  "scope": "markup.inserted",
  "settings": {
    "foreground": "#99C794"
  }
},
{
  "name": "Deleted",
  "scope": "markup.deleted",
  "settings": {
    "foreground": "#E15A60"
  }
},
{
  "name": "Changed",
  "scope": "markup.changed",
  "settings": {
    "foreground": "#BB80B3"
  }
}
```

**Pull request merged**
